# Generated by Django 6.0.2 on 2026-02-27 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.UUIDField()),
                ('alertType', models.CharField(choices=[('PREDICTIVE', 'PREDICTIVE'), ('REACTIVE', 'REACTIVE'), ('ANOMALY', 'ANOMALY'), ('SELF_HEAL', 'SELF_HEAL')], default='REACTIVE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('RESOLVED', 'RESOLVED')], default='ACTIVE', max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceId', models.UUIDField()),
                ('sourceType', models.CharField(choices=[('ATM', 'ATM'), ('PaymentChannel', 'PaymentChannel')], max_length=20)),
                ('anomalyType', models.CharField(choices=[('UNUSUAL_WITHDRAWAL', 'UNUSUAL_WITHDRAWAL'), ('CARD_SKIMMING', 'CARD_SKIMMING'), ('RAPID_FAILURES', 'RAPID_FAILURES'), ('MALWARE_PATTERN', 'MALWARE_PATTERN')], max_length=30)),
                ('confidenceScore', models.FloatField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('contributingLogIds', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceId', models.UUIDField()),
                ('sourceType', models.CharField(choices=[('ATM', 'ATM'), ('PaymentChannel', 'PaymentChannel')], max_length=20)),
                ('healthScore', models.FloatField()),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('DEGRADED', 'DEGRADED'), ('MAINTENANCE', 'MAINTENANCE')], max_length=20)),
                ('networkScore', models.FloatField()),
                ('hardwareScore', models.FloatField()),
                ('softwareScore', models.FloatField()),
                ('transactionScore', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('RESOLVED', 'RESOLVED')], default='OPEN', max_length=20)),
                ('sourceId', models.UUIDField()),
                ('sourceType', models.CharField(choices=[('ATM', 'ATM'), ('PaymentChannel', 'PaymentChannel')], max_length=20)),
                ('rootCauseCategory', models.CharField(choices=[('NETWORK', 'NETWORK'), ('CASH_JAM', 'CASH_JAM'), ('SWITCH', 'SWITCH'), ('SERVER', 'SERVER'), ('FRAUD', 'FRAUD'), ('TIMEOUT', 'TIMEOUT'), ('HARDWARE', 'HARDWARE'), ('UNKNOWN', 'UNKNOWN')], max_length=20)),
                ('aiConfidence', models.FloatField()),
                ('triggeringLogId', models.UUIDField()),
                ('contributingLogIds', models.JSONField(default=list)),
                ('assignedTo', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceType', models.CharField(choices=[('ATM', 'ATM'), ('PaymentChannel', 'PaymentChannel')], max_length=20)),
                ('sourceId', models.UUIDField()),
                ('timestamp', models.DateTimeField()),
                ('logLevel', models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], max_length=10)),
                ('eventCode', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('rawMessage', models.TextField()),
                ('transactionId', models.CharField(blank=True, max_length=100, null=True)),
                ('dedupHash', models.CharField(max_length=128)),
                ('incidentId', models.UUIDField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SelfHealAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidentId', models.UUIDField()),
                ('actionType', models.CharField(choices=[('RESTART_SERVICE', 'RESTART_SERVICE'), ('SWITCH_NETWORK', 'SWITCH_NETWORK'), ('FLUSH_CACHE', 'FLUSH_CACHE'), ('REROUTE_TRAFFIC', 'REROUTE_TRAFFIC'), ('ALERT_ENGINEER', 'ALERT_ENGINEER'), ('FREEZE_ATM', 'FREEZE_ATM')], max_length=30)),
                ('triggeredBy', models.CharField(choices=[('AUTO', 'AUTO'), ('MANUAL', 'MANUAL')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
