# Generated by Django 6.0.2 on 2026-02-28 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('serialNumber', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('DEGRADED', 'DEGRADED'), ('MAINTENANCE', 'MAINTENANCE')], default='ONLINE', max_length=20)),
                ('healthScore', models.FloatField(default=100.0)),
                ('networkScore', models.FloatField(default=100.0)),
                ('hardwareScore', models.FloatField(default=100.0)),
                ('softwareScore', models.FloatField(default=100.0)),
                ('transactionScore', models.FloatField(default=100.0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('lastSeen', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipientId', models.CharField(max_length=255)),
                ('channel', models.CharField(default='SMS', max_length=20)),
                ('message', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('body', models.TextField()),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='ONLINE', max_length=20)),
                ('endpoint', models.URLField(blank=True, default='')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
