# Generated by Django 6.0.2 on 2026-02-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0002_atm_customernotification_messagetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='logEntryId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='incidentDbId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='messageSent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='messageTemplateId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customernotification',
            name='sentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='resolvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='rootCauseDetail',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='logentry',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='channel',
            field=models.CharField(default='SMS', max_length=20),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='templateKey',
            field=models.CharField(default='atm_offline', max_length=50),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='variablesSchema',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('DELIVERED', 'DELIVERED')], default='SENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INVESTIGATING', 'INVESTIGATING'), ('AUTO_RESOLVED', 'AUTO_RESOLVED'), ('RESOLVED', 'RESOLVED'), ('ESCALATED', 'ESCALATED')], default='OPEN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='messagetemplate',
            unique_together={('templateKey', 'language', 'channel')},
        ),
    ]
