# Generated by Django 6.0.2 on 2026-03-13 08:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FailedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=50, unique=True)),
                ('phone_hash', models.CharField(db_index=True, max_length=64)),
                ('phone_last_four', models.CharField(max_length=4)),
                ('card_last_four', models.CharField(max_length=4)),
                ('amount', models.FloatField()),
                ('amount_dispensed', models.FloatField(default=0)),
                ('refund_amount', models.FloatField(default=0)),
                ('transaction_type', models.CharField(choices=[('WITHDRAWAL', 'WITHDRAWAL'), ('BALANCE_CHECK', 'BALANCE_CHECK'), ('DEPOSIT', 'DEPOSIT')], default='WITHDRAWAL', max_length=20)),
                ('failure_type', models.CharField(choices=[('CASH_JAM', 'CASH_JAM'), ('PARTIAL_DISPENSE', 'PARTIAL_DISPENSE'), ('NETWORK_TIMEOUT', 'NETWORK_TIMEOUT'), ('CARD_CAPTURED', 'CARD_CAPTURED')], default='CASH_JAM', max_length=30)),
                ('failure_reason', models.TextField()),
                ('failure_reason_hi', models.TextField(default='')),
                ('status', models.CharField(choices=[('DETECTED', 'DETECTED'), ('INVESTIGATING', 'INVESTIGATING'), ('ENGINEER_DISPATCHED', 'ENGINEER_DISPATCHED'), ('RESOLVING', 'RESOLVING'), ('REFUND_INITIATED', 'REFUND_INITIATED'), ('RESOLVED', 'RESOLVED')], default='DETECTED', max_length=30)),
                ('refund_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('NOT_APPLICABLE', 'NOT_APPLICABLE')], default='PENDING', max_length=20)),
                ('refund_eta', models.DateTimeField(blank=True, null=True)),
                ('engineer_name', models.CharField(blank=True, default='', max_length=100)),
                ('engineer_eta_minutes', models.IntegerField(default=0)),
                ('timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATM.atm')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATM.incident')),
            ],
        ),
        migrations.CreateModel(
            name='StatusToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('failed_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_tokens', to='ATM.failedtransaction')),
            ],
        ),
    ]
