# Generated by Django 6.0.2 on 2026-04-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0006_customersession_otptoken_failedtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledgedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
