# Generated by Django 6.0.2 on 2026-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0007_add_acknowledged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='escalationReason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
