# Generated by Django 6.0.2 on 2026-04-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0008_add_escalation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('ENGINEER', 'ENGINEER'), ('VIEWER', 'VIEWER')], default='ENGINEER', max_length=20),
        ),
    ]
