# Generated by Django 6.0.2 on 2026-04-06 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATM', '0009_add_viewer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsnapshot',
            name='sourceId',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='healthsnapshot',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assignedTo',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='createdAt',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(choices=[('LOW', 'LOW'), ('MEDIUM', 'MEDIUM'), ('HIGH', 'HIGH'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='incident',
            name='sourceId',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('INVESTIGATING', 'INVESTIGATING'), ('AUTO_RESOLVED', 'AUTO_RESOLVED'), ('RESOLVED', 'RESOLVED'), ('ESCALATED', 'ESCALATED')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='triggeringLogId',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='logLevel',
            field=models.CharField(choices=[('INFO', 'INFO'), ('WARN', 'WARN'), ('ERROR', 'ERROR'), ('CRITICAL', 'CRITICAL')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='sourceId',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cardHash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
